---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-next
spec:
  capacity:
    storage: 20Gi
  nfs:
    server: 10.53.101.100
    path: /k8s/forgejo-next
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - noatime
    - nfsvers=4.2
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-next
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: forgejo-next
  storageClassName: nfs
  volumeMode: Filesystem
