---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: '{{ .Release.Namespace }}-local-{{ .Values.name }}'
spec:
  capacity:
    storage: '{{.Values.capacity}}'
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: '/precious/k8s/{{ .Release.Namespace }}-{{ .Values.name }}'
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: forgejo.org/drbd
              operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Namespace }}-local-{{ .Values.name }}'
  namespace: '{{.Release.Namespace}}'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '{{.Values.capacity}}'
  storageClassName: local-storage
  volumeName: '{{ .Release.Namespace }}-local-{{ .Values.name }}'
  volumeMode: Filesystem
