---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-next-local-v{{ .Values.major }}
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /precious/k8s/forgejo-next-v{{ .Values.major }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: forgejo.org/drbd
              operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-next-local-v{{ .Values.major }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.capacity }}
  storageClassName: local-storage
  volumeName: forgejo-next-local-v{{ .Values.major }}
  volumeMode: Filesystem
