---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: '{{ .Release.Namespace }}-{{ .Values.name }}'
spec:
  capacity:
    storage: '{{.Values.capacity}}'
  nfs:
    server: '{{.Values.nfsServer}}'
    path: '/k8s/{{ .Release.Namespace }}-{{ .Values.name }}'
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - noatime
    - nfsvers=4.2
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Namespace }}-{{ .Values.name }}'
  namespace: '{{.Release.Namespace}}'
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: '{{.Values.capacity}}'
  volumeName: '{{ .Release.Namespace }}-{{ .Values.name }}'
  storageClassName: nfs
  volumeMode: Filesystem
