---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-next-v{{ .Values.major }}
spec:
  capacity:
    storage: {{.Values.capacity}}
  nfs:
    server: {{.Values.nfsServer}}
    path: /k8s/forgejo-next-v{{ .Values.major }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - noatime
    - nfsvers=4.2
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-next-v{{ .Values.major }}
  namespace: {{.Release.Namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.capacity}}
  volumeName: forgejo-next-v{{ .Values.major }}
  storageClassName: nfs
  volumeMode: Filesystem
