name: build

on:
  push:
  pull_request:

env:
  HUSKY: 0

jobs:
  lint-files:
    runs-on: docker-bookworm
    container:
      image: code.forgejo.org/forgejo-contrib/renovate:39.7.4@sha256:39812afb2d242da1aec2cc130b7a86a717dabeca40d5e74e57e632b3f429e4fa

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - name: ⚙️ Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          standalone: true

      - run: pnpm install
      - run: pnpm lint

  lint-renovate:
    runs-on: docker-bookworm
    container:
      image: code.forgejo.org/forgejo-contrib/renovate:39.7.4@sha256:39812afb2d242da1aec2cc130b7a86a717dabeca40d5e74e57e632b3f429e4fa

    strategy:
      matrix:
        file:
          - renovate.json

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - run: node bin/validator.cjs ${{ matrix.file }}
        env:
          LOG_LEVEL: debug
          RENOVATE_PLATFORM: gitea
          RENOVATE_ENDPOINT: ${{ github.server_url }}
