name: build

on:
  push:

jobs:
  lint-renovate:
    runs-on: docker-bookworm
    container:
      image: code.forgejo.org/forgejo-contrib/renovate:39.7.4@sha256:39812afb2d242da1aec2cc130b7a86a717dabeca40d5e74e57e632b3f429e4fa

    strategy:
      matrix:
        file:
          - renovate.json

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - run: node bin/validator.cjs ${{ matrix.file }}
        env:
          LOG_LEVEL: debug
          RENOVATE_PLATFORM: gitea
          RENOVATE_ENDPOINT: ${{ github.server_url }}
