name: build

on:
  push:
  pull_request:

env:
  HUSKY: 0
  HELM_VERSION: v3.16.2 # renovate: datasource=github-releases depName=helm packageName=helm/helm

jobs:
  lint:
    runs-on: docker-bookworm
    container:
      image: code.forgejo.org/forgejo-contrib/renovate:39.17.1@sha256:8e74c986e09f8ac4b10ed6cb125bd9ac7081ff9836eba6110d853154e7aabc85

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          show-progress: false

      - name: ⚙️ Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          standalone: true

      - name: ⚙️ Setup helm
        run: install-tool helm ${{ env.HELM_VERSION }}

      - run: pnpm install

      - run: pnpm markdownlint

      - run: pnpm prettier

      - run: pnpm lint:charts

      - run: node bin/validator.cjs renovate.json
        env:
          LOG_LEVEL: debug
          RENOVATE_PLATFORM: gitea
          RENOVATE_ENDPOINT: ${{ github.server_url }}
