---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-{{ .Values.pvc }}
  namespace: {{.Release.Namespace}}
spec:
  schedule: '@daily'
  jobTemplate:
    spec:
      template:
        automountServiceAccountToken: false
        enableServiceLinks: false
        spec:
          containers:
            - name: backup-{{ .Values.pvc }}

              image: quay.io/instrumentisto/rsync-ssh:alpine3.20

              command: ['/bin/sh']
              args:
                - -c
                - |
                  set -x
                  apk add coreutils
                  ssh -oStrictHostKeyChecking=no -p23 {{ .Values.storageBox }} mkdir -p {{ .Values.pvc }}
                  rsync -e 'ssh -oStrictHostKeyChecking=no -p23' -zvaHS --delete --link-dest ../../{{ .Values.pvc }}/backup-day-`date +%d -d yesterday`/  /data/ {{ .Values.storageBox }}:{{ .Values.pvc }}/backup-day-`date +%d`/

              volumeMounts:
                - name: data-volume
                  mountPath: /data
                  readOnly: true

                - name: sshdir
                  mountPath: /root/.ssh
                  readOnly: true

          volumes:
            - name: data-volume
              persistentVolumeClaim:
                claimName: {{.Values.pvc}}

            - name: sshdir
              secret:
                secretName: backup-ssh-key
                defaultMode: 0400
                items:
                  - key: ssh-privatekey
                    path: id_ed25519

          restartPolicy: Never
