apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forgejo-code
resources:
  - pvc.yaml
  - forgejo-code.yaml
  - forgejo-route.yaml
  - forgejo-data.yaml
  - backup.yaml
# https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
patches:
  - path: image.yaml
