apiVersion: v1
kind: Service
metadata:
  name: static-site-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: static-site-{{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: static-site-{{ .Release.Name }}
  ports:
    - port: 80
      targetPort: http
      name: http
