# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      # https://hub.docker.com/r/bitnamicharts/cert-manager/tags
      chart: cert-manager
      version: '1.3.24'
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bitnami-charts
      interval: 5m
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
---
# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-config
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ./flux/infrastructure/charts/cert-manager-config
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
  dependsOn:
    - name: cert-manager
      namespace: kube-system
  driftDetection:
    mode: enabled
  upgrade:
    crds: CreateReplace
