# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
spec:
  dependsOn:
    - name: metallb
      namespace: metallb-system
    - name: metallb-config
      namespace: metallb-system
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: traefik
      version: '31.1.1'
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: traefik-charts
      interval: 5m
  upgrade:
    crds: CreateReplace
  releaseName: traefik
  values:
    deployment:
      replicas: 2
    ports:
      web:
        port: 80
        redirectTo:
          port: websecure
          priority: 1
      ssh-code:
        port: 22
        # https://github.com/traefik/traefik-helm-chart/blob/v32.1.1/traefik/values.yaml#L611-L614
        # exposed means listens on the public IPs
        exposedPort: 22
        expose:
          default: true
      ssh-code-invisible:
        port: 2900
        # https://github.com/traefik/traefik-helm-chart/blob/v32.1.1/traefik/values.yaml#L611-L614
        # exposed means listens on the public IPs
        exposedPort: 2900
        expose:
          default: true
      ssh-next:
        port: 2020
        # https://github.com/traefik/traefik-helm-chart/blob/v32.1.1/traefik/values.yaml#L611-L614
        # exposed means listens on the public IPs
        exposedPort: 2020
        expose:
          default: true
      ssh-next-v7:
        port: 2070
        # https://github.com/traefik/traefik-helm-chart/blob/v32.1.1/traefik/values.yaml#L611-L614
        # exposed means listens on the public IPs
        exposedPort: 2070
        expose:
          default: true
      ssh-next-v8:
        port: 2080
        # https://github.com/traefik/traefik-helm-chart/blob/v32.1.1/traefik/values.yaml#L611-L614
        # exposed means listens on the public IPs
        exposedPort: 2080
        expose:
          default: true
      ssh-next-v9:
        port: 2090
        # https://github.com/traefik/traefik-helm-chart/blob/v32.1.1/traefik/values.yaml#L611-L614
        # exposed means listens on the public IPs
        exposedPort: 2090
        expose:
          default: true
      ssh-next-v10:
        port: 2100
        # https://github.com/traefik/traefik-helm-chart/blob/v32.1.1/traefik/values.yaml#L611-L614
        # exposed means listens on the public IPs
        exposedPort: 2100
        expose:
          default: true
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 188.40.16.47,2a01:4f8:fff2:48::2
      spec:
        externalTrafficPolicy: Local
        ipFamilyPolicy: PreferDualStack
    logs:
      general:
        level: INFO
      access:
        enabled: true
        fields:
          headers:
            # https://github.com/traefik/traefik-helm-chart/blob/v32.1.1/traefik/values.yaml#L365-L369
            names:
              User-Agent: keep
---
# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-config
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: ./flux/infrastructure/charts/traefik-config
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
  dependsOn:
    - name: traefik
  driftDetection:
    mode: enabled
