---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: forgejo-next-digest
  namespace: flux-system
spec:
  interval: 15m
  ref:
    branch: main
  url: https://code.forgejo.org/infrastructure/next-digest.git
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 15m
  ref:
    branch: main
  url: https://code.forgejo.org/infrastructure/k8s-cluster.git
  include:
    - repository:
        forgejo-next-digest
      toPath: flux/apps/digest
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
