---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 15m
  ref:
    branch: main
  url: https://codeberg.org/forgejo/k8s-cluster.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/clusters
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
