---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-next
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-repos
    - name: infra-controllers
    - name: infra-namespaces
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/forgejo-next
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-next-v7
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-repos
    - name: infra-controllers
    - name: infra-namespaces
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/forgejo-next-v7
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-next-v8
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-repos
    - name: infra-controllers
    - name: infra-namespaces
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/forgejo-next-v8
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-next-v9
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-repos
    - name: infra-controllers
    - name: infra-namespaces
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/forgejo-next-v9
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-next-v10
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-repos
    - name: infra-controllers
    - name: infra-namespaces
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/forgejo-next-v10
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: forgejo-next-common
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-repos
    - name: infra-controllers
    - name: infra-namespaces
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/forgejo-next-common
  prune: true
  wait: true
