---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: static-site
  namespace: static-site
spec:
  dependsOn:
    - name: infra-controllers
    - name: infra-namespaces
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/static-site
  prune: true
  wait: true
