---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: $pvc_name
spec:
  capacity:
    storage: $pvc_capacity
  nfs:
    server: $node_nfs_server
    path: /k8s/$pvc_name
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - noatime
    - nfsvers=4.2
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $pvc_name
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: $pvc_capacity
  volumeName: $pvc_name
  storageClassName: nfs
  volumeMode: Filesystem
