deployment:
  replicas: 2
ports:
  web:
    port: 80
    redirectTo:
      port: websecure
      priority: 1
  ssh-next:
    port: 2020
    exposedPort: 2020
    # https://github.com/traefik/traefik-helm-chart/blob/v32.1.1/traefik/values.yaml#L611-L614
    expose:
      default: true
service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: $failover_ipv4,$failover_ipv6
  spec:
    externalTrafficPolicy: Local
    ipFamilyPolicy: PreferDualStack
logs:
  general:
    level: INFO
  access:
    enabled: true
    fields:
      headers:
        # https://github.com/traefik/traefik-helm-chart/blob/v32.1.1/traefik/values.yaml#L365-L369
        names:
          User-Agent: keep
