# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: f3-documentation
spec:
  interval: 30m
  chart:
    spec:
      chart: ./flux/apps/charts/static-site
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
  values:
    git: https://code.forgejo.org/f3/html-documentation
    sha: 8d8d7387fc46bd96abe90502305117350656949a
    host: f3.forgefriends.forgejo.org
