---
# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-pvc-v10
spec:
  interval: 30m
  chart:
    spec:
      chart: ./flux/apps/charts/pvc
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
  values:
    major: '10'
  driftDetection:
    mode: enabled
