apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-v10
spec:
  values:
    image:
      digest: 'sha256:cf0a34c0e66821da6d9e3904de2510e90e6ed76ebc6789e4f66550201d447e75'
