apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-v7
spec:
  values:
    image:
      digest: 'sha256:5c3bb891172637bd6b98f8a52a194914ba8b7c5314a9dcf70aebc3504c9bacb4'
