apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-v9
spec:
  values:
    image:
      digest: 'sha256:019ad5e792027ccd751e34c20c97807ea0f5fcc4bd52fc0185775d7b6b3508e1'
