# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  values:
    image:
      digest: 'sha256:7b9dbe9ab4cd2112d7da22ad219373064aace673526fbb42df8fb7777a3090a4'
