# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-v8
spec:
  interval: 30m
  chart:
    spec:
      # https://code.forgejo.org/forgejo-helm/-/packages/container/forgejo/versions
      chart: forgejo
      version: '9.0.0'
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: forgejo
      interval: 5m
  # https://fluxcd.io/flux/components/helm/helmreleases/#values-references
  valuesFrom:
    - kind: Secret
      name: forgejo-next-username-and-password
    - kind: Secret
      name: forgejo-next-posteo-mailer
  values:
    strategy:
      type: 'Recreate'

    image:
      registry: codeberg.org
      repository: forgejo-experimental/forgejo
      tag: '8'
      # replaced by ../digest/v8.yaml
      digest: ''

    ingress:
      enabled: true
      annotations:
        # https://doc.traefik.io/traefik/v3.1/routing/providers/kubernetes-ingress/#on-ingress
        # reference middlewares via `<namspace>-<name>@kubernetescrd`
        #traefik.ingress.kubernetes.io/router.middlewares: default-forgejo-ratelimit@kubernetescrd
        # https://cert-manager.io/docs/usage/ingress/#supported-annotations
        # https://github.com/cert-manager/cert-manager/issues/2239
        cert-manager.io/cluster-issuer: letsencrypt-http
        cert-manager.io/private-key-algorithm: ECDSA
        cert-manager.io/private-key-size: 384
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls:
        - hosts:
            - v8.next.forgejo.org
          secretName: tls-forgejo-next-v8-ingress-http
      hosts:
        - host: v8.next.forgejo.org
          paths:
            - path: /
              pathType: Prefix

    service:
      http:
        type: ClusterIP
        ipFamilyPolicy: PreferDualStack
        clusterIP: ~
      ssh:
        type: ClusterIP
        clusterIP: ~
        ipFamilyPolicy: PreferDualStack

    redis-cluster:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false

    persistence:
      enabled: true
      create: false
      claimName: forgejo-next-v8

    gitea:
      # initial admin user and password from forgejo-next-username-and-password
      config:
        APP_NAME: "FOR TESTING ONLY, ALL DATA CAN BE WIPED OUT AT ANY TIME"
        server:
          ROOT_URL: https://v8.next.forgejo.org/
          DOMAIN: v8.next.forgejo.org
          SSH_DOMAIN: v8.next.forgejo.org
          SSH_PORT: "2080"
          LFS_START_SERVER: true
        service:
          REGISTER_EMAIL_CONFIRM: true
          DEFAULT_KEEP_EMAIL_PRIVATE: true
          ENABLE_NOTIFY_MAIL: true
        federation:
          ENABLED: true
        admin:
          SEND_NOTIFICATION_EMAIL_ON_NEW_USER: true
        cors:
          ENABLED: true
          ALLOW_DOMAIN: "*"
          HEADERS: "Access-Control-Allow-Origin"
        mailer:
          ENABLED: true
          FROM: "forgejo-next@posteo.com"
          PROTOCOL: "smtp+starttls"
          SMTP_ADDR: "posteo.de"
          SMTP_PORT: "587"
          # user and password from forgejo-next-posteo-mailer
        database:
          DB_TYPE: sqlite3
        session:
          PROVIDER: db
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
        indexer:
          ISSUE_INDEXER_TYPE: bleve
          REPO_INDEXER_ENABLED: true
        openid:
          ENABLE_OPENID_SIGNIN: true
          ENABLE_OPENID_SIGNUP: true
        cron.archive_cleanup:
          SCHEDULE: "@hourly"
          OLDER_THAN: "2h"
