---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: forgejo-next-local
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: forgejo.org/drbd
              operator: Exists
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: forgejo-next-local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
  volumeMode: Filesystem
