apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-charts
  namespace: flux-system # needed for renovate
spec:
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts
