# Route from traefik to forgejo
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: forgejo-next-ssh
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - ssh-next # name from traefik port
  routes:
    - match: HostSNI(`*`)
      services:
        - name: forgejo-next-ssh
          port: ssh # forgejo ssh port on kubernetes service
