# https://fluxcd.io/flux/components/helm/helmreleases/
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
spec:
  interval: 30m
  chart:
    spec:
      # https://code.forgejo.org/forgejo-helm/-/packages/container/forgejo/versions
      chart: forgejo
      version: '10.0.0'
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: forgejo
      interval: 5m
  releaseName: forgejo
  # https://fluxcd.io/flux/components/helm/helmreleases/#values-references
  valuesFrom:
    - kind: Secret
      name: forgejo-next-username-and-password
    - kind: Secret
      name: forgejo-next-mailer
  values:
    strategy:
      type: 'Recreate'

    image:
      registry: codeberg.org
      repository: forgejo-experimental/forgejo
      tag: '8.0-test'
      # to be used for implementing updates https://code.forgejo.org/infrastructure/k8s-cluster/issues/18
      digest: ''
      rootless: false

    ingress:
      enabled: true
      annotations:
        # https://doc.traefik.io/traefik/v3.1/routing/providers/kubernetes-ingress/#on-ingress
        # reference middlewares via `<namspace>-<name>@kubernetescrd`
        traefik.ingress.kubernetes.io/router.middlewares: default-forgejo-ratelimit@kubernetescrd
        # https://cert-manager.io/docs/usage/ingress/#supported-annotations
        # https://github.com/cert-manager/cert-manager/issues/2239
        cert-manager.io/cluster-issuer: letsencrypt-http
        cert-manager.io/private-key-algorithm: ECDSA
        cert-manager.io/private-key-size: 384
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls:
        - hosts:
            - next.forgejo.org
          secretName: tls-forgejo-next-ingress-http
      hosts:
        - host: next.forgejo.org
          paths:
            - path: /
              pathType: Prefix

    service:
      http:
        type: ClusterIP
        ipFamilyPolicy: PreferDualStack
        clusterIP: ~
      ssh:
        port: ssh
        type: ClusterIP
        clusterIP: ~
        ipFamilyPolicy: PreferDualStack

    redis-cluster:
      enabled: false
    postgresql:
      enabled: false
    postgresql-ha:
      enabled: false

    persistence:
      enabled: true
      create: false
      claimName: forgejo-next

    gitea:
      config:
        APP_NAME: "Forgejo v8.0 demo"
        APP_SLOGAN: "ARCHIVED USE v8.next.forgejo.org instead"
        APP_DISPLAY_NAME_FORMAT: "{APP_NAME} [{APP_SLOGAN}]"
        log:
          LEVEL: "info"
        server:
          ROOT_URL: https://next.forgejo.org/
          DOMAIN: next.forgejo.org
          SSH_DOMAIN: next.forgejo.org
          SSH_PORT: "2020"
          LFS_START_SERVER: true
          OFFLINE_MODE: true
        repository:
          ROOT: /data/git/repositories
        service:
          REGISTER_EMAIL_CONFIRM: true
          DEFAULT_KEEP_EMAIL_PRIVATE: true
          ENABLE_NOTIFY_MAIL: true
          DISABLE_REGISTRATION: true
        actions:
          ENABLED: false
        mirror:
          ENABLED: false
        federation:
          ENABLED: true
        admin:
          SEND_NOTIFICATION_EMAIL_ON_NEW_USER: true
        cors:
          ENABLED: true
          ALLOW_DOMAIN: "*"
          HEADERS: "Access-Control-Allow-Origin"
        mailer:
          ENABLED: true
          FROM: "noreply@forgejo.org"
          PROTOCOL: "smtp+starttls"
          SMTP_ADDR: "ssl0.ovh.net"
          SMTP_PORT: "587"
        database:
          PATH: /data/gitea.db
          DB_TYPE: sqlite3
        session:
          PROVIDER: db
        cache:
          ADAPTER: memory
        queue:
          TYPE: level
        indexer:
          REPO_INDEXER_ENABLED: true
        cron.archive_cleanup:
          SCHEDULE: "@hourly"
          OLDER_THAN: "2h"
