apiVersion: v2
name: metallb-config
version: 1.0.0 # need increment on any manifest change
description: MetalLB configurations
icon: https://raw.githubusercontent.com/metallb/metallb/abad99eb4ffe095f0c8a3878b684fe919ab84764/website/static/images/logo/metallb-blue.svg
