strategy:
  type: 'Recreate'

ingress:
  enabled: true
  annotations:
    # https://cert-manager.io/docs/usage/ingress/#supported-annotations
    # https://github.com/cert-manager/cert-manager/issues/2239
    cert-manager.io/cluster-issuer: letsencrypt-http
    cert-manager.io/private-key-algorithm: ECDSA
    cert-manager.io/private-key-size: 384
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure

service:
  http:
    type: ClusterIP
    ipFamilyPolicy: PreferDualStack
    clusterIP: ~
  ssh:
    type: ClusterIP
    clusterIP: ~
    ipFamilyPolicy: PreferDualStack

redis-cluster:
  enabled: false
postgresql:
  enabled: false
postgresql-ha:
  enabled: false

persistence:
  enabled: true
  create: false
